### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by ssoonmi** [maggiecs/Snapshot#1]
Following and Photofeed
- [x] specify that a `user` can follow other `users` that will determine what shows up on that `user`'s dashboard

Instead of `images` maybe make `posts` instead. Because on the actual Instagram website, a single `post` can have multiple `images`. Separating `images` and `posts` may be a good idea if you want to implement this feature later on.

**Comment by ssoonmi** [comment]
typo on: "Users have a private dashboard of their followed user's images"
I think you wanted to say " users' ", instead of " user's "

**Comment by ssoonmi** [comment]
- [x] Instagram posts should have the ability to include a description.

**Comment by maggiecs** [comment]
I thought about the description before but isn't the description just a comment?

**Comment by maggiecs** [comment]
Nevermind. I realize that the description is different from a comment because you can edit it.
